### ISSUE TITLE
Port the OAuth component to a service like OAuth.io, and remove the server altogether.

### ISSUE THREAD

**Issue by UnquietCode** [UnquietCode/Tumblr-Likes-Grid#6]
Currently the app requires the PHP server only for OAuth authentication. It should be possible to get rid of it and do all of the API calls to Tumblr in the browser.

-------------

I think the best way to do this is to first get the code from GitHub. Then, instead of using a server to talk to Tumblr use something like OAuth.io instead. They handle the heavy lifting while you just write some JavaScript to call their API. You would need to register an app with Tumblr first.

You will probably want a tool to view the webpage while you are tinkering with it. Brace and similar services can turn a dropbox folder into a hosted website. If it works out, I’m happy to continue hosting it under the old url.

**Comment by UnquietCode** [comment]
I've started a bounty for $75:

https://www.bountysource.com/issues/15132434-create-a-bounty-for-someone-to-port-the-oauth-and-make-this-baby-server-less

**Comment by pyk** [comment]
@UnquietCode any progress on this bounty?

I have some experiences building a server-less web apps which only talk to some API providers like OAuth.io. I'm interested to tackling the bounty. but before any further, i would like to confirm and i need  some information from you.

First, I wonder about status of this bounty. Are this bounty depreceated? I'm afraid that on [README][rd] it says that the project is depreceated. 

Second, it seems that you want to remove all server stuff. So it means that you want to port this porject as a static site(server-less) right? which i need restructure of this tree project to a compatible static site like this (only an example):

```
.
├── index.html
├── assets
│   └── {template,image,js,css,libs} (all assets belong here)
├── scripts
│   └── (*.coffe belong here)
```
Am i right?

[rd]: https://github.com/UnquietCode/Tumblr-Likes-Grid/blob/master/README.md

**Comment by UnquietCode** [comment]
Hey there. So the bounty is still good -- they have my bitcoins still. I set aside the funds because the community really seems to enjoy what this tool has to offer, but I don't have the time to actively develop it. An overhaul like this is beyond the scope of my open-sorcery. The main reason it is deprecated is because I can't afford to run a PHP web server. If you make the changes towards a static site then I've pledged to continue hosting it again. If you are interested in helping, you should feel free to fork the project and restructure it as necessary!

**Comment by pyk** [comment]
@UnquietCode thanks for your confirmation! :smile:
I'am working on this right now. I will keep you notified my progress on this issue :+1:

**Comment by pyk** [comment]
@UnquietCode Ben, PR #7 should address this bounty. 

Can you please close this issue? so i can claim the bounty https://www.bountysource.com/issues/15132434 . 

Thanks ben :+1:

**Comment by UnquietCode** [comment]
Sorry I haven't had a chance to merge this in yet. But it looks great and I will release the bounty to you. Thanks for your efforts!

**Comment by pyk** [comment]
Thanks @UnquietCode !
